services:
  app:
    build: .
    container_name: surf-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://surfadmin:surfadmin@mongo:27017/surf-app?authSource=admin
    depends_on:
      - mongo
    networks:
      - surf-network

  mongo:
    image: mongo:6
    container_name: surf-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: surfadmin
      MONGO_INITDB_ROOT_PASSWORD: surfadmin
    volumes:
      - mongo_data:/data/db
    networks:
      - surf-network

volumes:
  mongo_data:
    driver: local

networks:
  surf-network:
    driver: bridge
